test: Work around header conflict between GNU setjmp and gnu-efi headers.
The GNU setjmp.h header and the gnu-efi efisetjmp_arch.h file both define
a global variable called 'jmp_buf'. This commit resolves this conflict by
abandoning the efi.h uber-include file. Instead we now pull in only the
gnu-efi headers we need for the tests. This resolves the conflict.

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>

Relevant error text:

/usr/include/efi/x86_64/efisetjmp_arch.h:20:23: error: conflicting types for ‘jmp_buf’
 } ALIGN(JMPBUF_ALIGN) jmp_buf;
                       ^~~~~~~
In file included from test/tcti-uefi-init_unit.c:8:0:
/usr/include/setjmp.h:48:30: note: previous declaration of ‘jmp_buf’ was here
 typedef struct __jmp_buf_tag jmp_buf[1];
                              ^~~~~~~
/usr/include/efi/efisetjmp.h:12:14: error: conflicting types for ‘_setjmp’
 extern UINTN setjmp(jmp_buf *env);
              ^
/usr/include/setjmp.h:63:12: note: previous declaration of ‘_setjmp’ was here
 extern int _setjmp (struct __jmp_buf_tag __env[1]) __THROWNL;